# Домашнее задание «Библиотека numpy. Вычислительные задачи»

## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

# первый способ

n = 10
np.arange(n - 1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [2]:
# второй способ

n = 10
a = np.arange(0, n)
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
n = 5
a2 = np.arange(0, n)
b2 = np.flip(a2)
np.diag(b2)

array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [4]:
# поскольку матрица диагональная, то самый простой вариант суммирования значений на диагонали
b2.sum()

10

In [5]:
# более общий случай
n = 5
a2 = np.arange(0, n)
b2 = np.flip(a2)
с2 = np.diag(b2)
sum(с2[i][i] for i in range(n))

10

## Задание 3
Решите систему уравнений:

* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [6]:
# коэффициенты при переменных в левой части уравнения

a3 = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [7]:
# значения в правой части уравнения

b3 = np.array( [4, 12, -3] )

In [8]:
# решение

from numpy import linalg

linalg.solve(a3, b3)

array([ 0.46666667,  3.84444444, -5.55555556])

In [9]:
# проверка верности

np.allclose( np.dot(a3, linalg.solve(a3, b3)), b3 )

True

## Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [10]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [11]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [12]:
def cosine(a, b):
    
    aLength = np.linalg.norm(a)
    bLength = np.linalg.norm(b)
    
    return np.dot(a, b) / ( aLength * bLength )

similarity = 0
best_similar_user = 0

for user in users_stats:
    if cosine(user, next_user_stats) > similarity:
        similarity = cosine(user, next_user_stats)
        best_similar_user = user
        
print('Самый похожий пользователь: ', best_similar_user, '; степень схожести:', round(similarity,2))

Самый похожий пользователь:  [0 1 1 0 0 0] ; степень схожести: 0.95
